### ISSUE TITLE
Problem: clean installs fails using stable/1.6.x

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/ansible-role-archivematica-src#108]
When using the stable/1.6.x ansible branch, I get this error:
`
    virtualbox-ovf: TASK [archivematica-src : include variables from retrieved dependencies files in namespace storage_service] ***
    virtualbox-ovf: fatal: [default]: FAILED! => {"failed": true, "msg": "No filename was specified to include.\n\nThe error appears to have been in '/home/username/workspace/deployment/packer/templates/vagrant-box-archivematica/provisioning/roles/archivematica-src/tasks/ss-osdeps.yml': line 35, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# create a namespace for osdeps file variables\n- name: \"include variables from retrieved dependencies files in namespace storage_service\"\n  ^ here\n"}
`

AM branch is stable/1.6.x and ss is stable/0.10.x. I'm using ansible 2.1.4.0

**Comment by sevein** [comment]
So this is the task causing the error:

```yml
- name: "include variables from retrieved dependencies files in namespace storage_service"
  include_vars: 
    file: "{{ tmpdirname }}/osdeps/archivematica-storage-service/{{ osdeps_file }}"
    name: "storage_service"
  when: osdeps
```
