### ISSUE TITLE
problem: qa/1.7.x branch error on role dependency (geerlingguy.nodejs)

### ISSUE THREAD

**Issue by hakamine** [artefactual-labs/ansible-role-archivematica-src#151]
Getting an error like this when the role dependency is executing:

```
TASK [geerlingguy.nodejs : Create npm global directory] ********************************************************
...
    "mode": "0755",
    "msg": "chown failed: failed to look up user hector",
    "owner": "root",
    "path": "/usr/local/lib/npm",
    "size": 4096,
    "state": "directory",
    "uid": 0
}
```

**Comment by hakamine** [comment]
This happens due to a bug in https://github.com/geerlingguy/ansible-role-nodejs/blob/4.1.1/tasks/main.yml#L8-L11 : 

```
- name: Define nodejs_install_npm_user
  set_fact:
    nodejs_install_npm_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  when: nodejs_install_npm_user is not defined
```

In recent versions of ansible (testing with 2.3.x) ansible_user is not defined (being replaced by `ansible_user_id`) so `nodejs_install_npm_user` is assigned the user on the ansible control machine. This fails if we are using a different user in the ansible target machine.  

It's worth noting that this problem does not happen when doing a vagrant deployment using the archivematica playbook in deploy-pub (https://github.com/artefactual/deploy-pub/tree/master/playbooks/archivematica), but will likely happen when doing deployments when the ansible control machine and target machine are different. 

Workaround is to assign `ansible_user_id` to `nodejs_install_npm_user` in the playbook vars, for example when invoking the archivematica-src playbook:

```
    - { role: "external-roles/artefactual.archivematica-src", 
        tags: ["archivematica-src"], 
        become: yes, 
        nodejs_install_npm_user: "{{ ansible_user_id }}"
        }
```
