### ISSUE TITLE
gunicorn config files are copied from the AM/SS source code repository, not created from templates

### ISSUE THREAD

**Issue by hakamine** [artefactual-labs/ansible-role-archivematica-src#175]
In the stable/1.6.x branch of the role, the gunicorn configuration files were created from templates, like this:

```
- name: "Template gunicorn configuration file"
  template:
    src: "etc_archivematica_storage-service.gunicorn-config.py.j2"
    dest: "/etc/archivematica/storage-service.gunicorn-config.py"
    backup: "yes"
  tags: "amsrc-ss-websrv"
```

In the qa/1.7.x branch, the config file is copied straight from the SS repo like this:

```
- name: "Copy gunicorn configuration file"
  copy:
    src: "{{ archivematica_src_dir }}/archivematica-storage-service/install/storage-service.gunicorn-config.py"
    dest: "{{ archivematica_src_ss_gunicorn_config }}"
    backup: "yes"
    force: "yes"
    remote_src: "yes"
  tags: "amsrc-ss-websrv"
```

Was this done for a reason? The potential problem is that if some installation needed its config tweaked, the configuration will be reset when doing a re-deploy.
