### ISSUE TITLE
Problem: Update Ansible Role for new createtransfers path and commands

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/ansible-role-archivematica-src#180]
The sampledata createtransfers script has been modified and will no longer run once the repository for that has been checked out by this role. 

Currently we call [the following](https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/tasks/main.yml#L121-L137): 
```
#
# archivematica-sampledata
#

- name: "Checkout out archivematica-sampledata repository"
  git:
    repo: "https://github.com/artefactual/archivematica-sampledata.git"
    dest: "~/archivematica-sampledata"
    update: "yes"
    depth: 1
  when: "archivematica_src_install_sample_data|bool"
  become: "no"

- name: "Generate special sampledata transfers"
  command: "~/archivematica-sampledata/createtransfers.py create-variously-encoded-files"
  when: "archivematica_src_install_sample_data|bool"
  become: "no"
```
This I believe can be changed to:
```
#
# archivematica-sampledata
#

- name: "Checkout out archivematica-sampledata repository"
  git:
    repo: "https://github.com/artefactual/archivematica-sampledata.git"
    dest: "~/archivematica-sampledata"
    update: "yes"
    depth: 1
  when: "archivematica_src_install_sample_data|bool"
  become: "no"

- name: "Generate special sampledata transfers"
  command: "~/archivematica-sampledata/createtransfers/createtransfers.py {{ item }}"
  with_items:
  - create-variously-encoded-files
  - create-deep-transfers
  - create-large-test-transfers
  when: "archivematica_src_install_sample_data|bool"
  become: "no"
```
Source for the multiple-item command: https://stackoverflow.com/a/24860054

**NB.** The path to the command has changed as well. 

The command `create-large-test-transfers` might need to be run at the user's request, i.e. it creates a lot of data, and it might not be desirable to create this every time as deployments could become slow. 

@scollazo @hakamine @mamedin - are one of you okay to coordinate this update? Let me know if I can test in any way.
