### ISSUE TITLE
Problem:  virus scan fails on default centos installs

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/ansible-role-archivematica-src#185]
In Centos environments, clamav listens on port 3310. 

We need to add ``  ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_SERVER=localhost:3310`` to /etc/sysconfig/archivematica-mcp-client on Centos

As a workaround, adding
```
archivematica_src_am_mcpclient_environment:
  DJANGO_SETTINGS_MODULE: "settings.common"
  ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_SERVER: "localhost:3310"
  ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_SEARCH_ENABLED: "{{ archivematica_src_search_enabled }}"

```

to the host vars, deploys the expected configurations.
