### ISSUE TITLE
Problem: task "Start rng-tools" uses wrong service name

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/ansible-role-archivematica-src#194]
Currently the task is:

```yaml
---
- name: "Start rng-tools (Ubuntu 16.04)"
  service:
    name: "rngd"
    state: "restarted"
    enabled: "yes"
  tags: "rng-tools"
  when:
    - osdeps
    - storage_service is defined
    - storage_service.osdeps_packages is defined
    - storage_service.osdeps_packages
    - ansible_distribution == "Ubuntu"
    - ansible_service_mgr == "systemd"
```

The service name should be `rng-tools` instead of `rngd`.
