### ISSUE TITLE
Broken tasks: pip install fails if lib/ is missing

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/ansible-role-archivematica-src#81]
Two pip tasks use `--find-links lib` which break if `lib/` is missing. This is now occurring in `stable/0.9.x` and `qa/0.x`.

```yml
- name: "Create virtualenv for archivematica-storage-service, pip install requirements"
  pip:
    chdir: "{{ archivematica_src_dir }}/archivematica-storage-service"
    requirements: "requirements.txt"
    virtualenv: "/usr/share/python/archivematica-storage-service"
    state: "latest"
  tags: "amsrc-ss-pydep"

- name: "Work around to install pip deps commented out in old SS branches"
  pip:
    chdir: "{{ archivematica_src_dir }}/archivematica-storage-service"
    virtualenv: "/usr/share/python/archivematica-storage-service"
    extra_args: "--find-links lib"
    state: "latest"
    name: "{{ item }}"
  with_items:
    - "python-swiftclient"
    - "python-keystoneclient"
    - "sword2"
    - "pyopenssl"
    - "ndg-httpsclient"
    - "pyasn1"
  when: "archivematica_src_ss_pip_missing_deps"
  tags: "amsrc-ss-pydep"
```

This is the solution I have tested:

```yml
- stat:
    path: "{{ archivematica_src_dir }}/archivematica-storage-service/lib"
  register: "ss_lib_dir_check"
- set_fact:
    ss_pip_install_extra_args: ""
- set_fact:
    ss_pip_install_extra_args: "--find-links lib"
  when: "ss_lib_dir_check.stat.isdir is defined and ss_lib_dir_check.stat.isdir"

- name: "Create virtualenv for archivematica-storage-service, pip install requirements"
  pip:
    chdir: "{{ archivematica_src_dir }}/archivematica-storage-service"
    requirements: "requirements.txt"
    virtualenv: "/usr/share/python/archivematica-storage-service"
    extra_args: "{{ ss_pip_install_extra_args }}"
    state: "latest"
  tags: "amsrc-ss-pydep"

- name: "Work around to install pip deps commented out in old SS branches"
  pip:
    chdir: "{{ archivematica_src_dir }}/archivematica-storage-service"
    virtualenv: "/usr/share/python/archivematica-storage-service"
    extra_args: "{{ ss_pip_install_extra_args }}"
    state: "latest"
    name: "{{ item }}"
  with_items:
    - "python-swiftclient"
    - "python-keystoneclient"
    - "sword2"
    - "pyopenssl"
    - "ndg-httpsclient"
    - "pyasn1"
  when: "archivematica_src_ss_pip_missing_deps"
  tags: "amsrc-ss-pydep"
```
